### ISSUE TITLE
Error while running terraform apply on 200-openshift-gitops directory

### ISSUE THREAD

**Issue by dimallya** [IBM/automation-turbonomic#12]
While following the steps provided in latest documentation, during `terraform apply` on _200-openshift-gitops_ directory getting following error: 
<img width="1095" alt="Screenshot 2022-06-02 at 1 57 32 PM" src="https://user-images.githubusercontent.com/99815425/171618958-c380b5a7-c9a4-4c2b-afe4-4e014c461550.png">

**Comment by vksuktha** [comment]
We tested on ARO & ROSA and getting same error.

**Comment by mjperrins** [comment]
@tcskill @seansund @triceam you able to see if there is a upstream issue here

**Comment by mjperrins** [comment]
@vksuktha can you check you GitHub PAT ?

**Comment by triceam** [comment]
From that screenshot, it looks like the git host and git repo were not set properly.  Both values are blank.  These need to be set in the tfvars file before executing the module.

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/974294/171628289-dc5c3f36-aec5-43a8-9fd2-d828aec57ea2.png">

This is also explained in step 3 of the turbonomic installation steps: https://github.com/IBM/automation-turbonomic#installing-turbonomic

**Comment by triceam** [comment]
@seansund  and I met with Anand and got to the bottom of this issue. This is not a regression.  

There are 3 main takeaways:

- Do not run the `setupWorkspace.sh` command using `sudo`.  You should not need to use `sudo` on any of our automation scripts.
- The `/workspaces` folder had root ownership, not the current `devops` user.  (Hence why `sudo` was being used).  This is an artifact from an older version of the launch script that used a different container image.  If you run into this same issue, you need to delete the `workspace` volume from docker.  To do this: 
  1. exit the container
  2. run `docker volume rm workspace` to get rid of the old volume
  3. re-launch using `launch.sh`  and re-run `setupWorkspace.sh`
  
  This error will not happen for new users.  It can only happen if you have previously used older versions of the launch script that created/mounted the workspace volume as root.
- Do not include quotes in the `credentials.properties` file
